### ISSUE TITLE
What are the code-code and user-user network model?

### ISSUE THREAD

**Issue by paulgirard** [edgeryders/ryderex#10]
Can you confirm the network model ?
_assume that we already filter the DB for one corpus only_

The code network model: 
(:code) - [:COOCCURS] - (:code)

The user network model ?
I tried : (:user) - [:TALKED_OR_QUOTED] - (:user) but that does not brings nothing.
Should we calculat user cooccurrences in topics (through posts) ? 
Or ?

**Comment by aerugo** [comment]
Yes, that is correct for COOCCURS. Remember that there can be multiple COOCCURS between two code nodes - one per corpus the codes co-occur in. A code can occur in multiple corpora. 

We always use the cooccurs count for the entire corpus, so there is no need to recalculate it based on the context.

<img width="475" alt="Screenshot 2021-06-04 at 11 36 34" src="https://user-images.githubusercontent.com/7785081/120782387-3eedc400-c52a-11eb-8ef9-2f69dac47b3c.png">

(:user)-[:TALKED_OR_QUOTED]->(:user)
This seems to work for me. You don't get the same?

<img width="626" alt="Screenshot 2021-06-04 at 11 40 52" src="https://user-images.githubusercontent.com/7785081/120782259-2087c880-c52a-11eb-9554-25ff30f6888c.png">

<img width="473" alt="Screenshot 2021-06-04 at 11 43 23" src="https://user-images.githubusercontent.com/7785081/120782246-1bc31480-c52a-11eb-9fc8-15de10873976.png">

**Comment by paulgirard** [comment]
Yes ok. We just forgot that relation when building corpus graph.
