### ISSUE TITLE
Labels not working correctly after following URL with state

### ISSUE THREAD

**Issue by aerugo** [edgeryders/ryderex#21]
Label density does not appear as expected when open the dashboard with a state in the URL.

This configuration:

<img width="2515" alt="Screenshot 2021-07-28 at 12 13 01" src="https://user-images.githubusercontent.com/7785081/127305993-204a9965-c7cf-46d4-b4f9-8d9a8d4e7630.png">

Is represented by its state URL (https://edgeryder.ouestware.com/dashboard/edgeryders/ethno-opencare?m=cn%7Cpi&cn.weightFilter=3&cn.mode=scopeArea&pi.weightFilter=5&sc.user=x%C2%9C%2B-N-%C2%8A7255%C2%AC)%05%C2%B1L%011%C2%BC%05%C2%BB), which displays this dashboard when opened in a new session. Note that changing the density slider does not seem to work as expected when opened through the state URL.

<img width="2515" alt="Screenshot 2021-07-28 at 12 16 57" src="https://user-images.githubusercontent.com/7785081/127306182-00968b4e-1ac7-404f-9d44-886cbfed4619.png">

<img width="2515" alt="Screenshot 2021-07-28 at 12 18 41" src="https://user-images.githubusercontent.com/7785081/127306469-b14f9cfe-55e4-48a2-9703-175cb92ff209.png">

**Comment by paulgirard** [comment]
Label controls were not stored in state yet.
