### ISSUE TITLE
Data List Component

### ISSUE THREAD

**Issue by paulgirard** [edgeryders/ryderex#5]
Retrieve data from API and show a paginated list of metadata.

Should we use an existing data table component ?
### Codes

- name
- description
- Created at
- annotation count in corpus (do _not_ use the global annotation count here! Instead, look at the IN_CORPUS relation from the code to the tag/corpus node and look at the annotation count property stored in that relation)

### Posts

- Content (truncated extract of "raw" property)
- Link to post on platform (platform URL + '/p/' + 'post_id')
- topic_title (title)
- Link to topic on platform (platform URL + '/t/' + 'topic_id')
- Created at
- Word count (word_count property on the post node)
- Author (username)

! Topic name could be a link directly to the topic on the platform

### Participants 

- username
- profile URL (platform URL + '/u/' + username)

### Annotations 

- Quote
- Created at
- Annotator (username)

## Actions

- change page
- sort by column
- select items
- filter by column ?
- chose column to be displayed ?

## Relations to focus

see dedicated issue #7

**Comment by aerugo** [comment]
@paulgirard - I have added fields to the table definitions above. I realized that I will need to update the database a little. I will do that in the next two weeks.

**Comment by aerugo** [comment]
I have now added:
- usernames to annotations and posts
- topic title to posts
- annotation count per code per corpus, stored as a property on the IN_CORPUS relation between codes and corpus nodes
